name: aigrove
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  geocoding: ^3.0.0

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  font_awesome_flutter: ^10.9.0
  google_fonts: ^6.3.0
  fl_chart: ^0.69.0
  supabase_flutter: ^2.9.1
  image_picker: ^1.0.4
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  tflite_flutter: ^0.11.0
  camera: ^0.10.5+5
  image: ^4.1.3
  path_provider: ^2.1.1
  path: ^1.8.3
  http: ^1.5.0
  google_generative_ai: ^0.2.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png" # I-replace ni sa path sa imong logo
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF" # Optional background color for Android adaptive icons
  adaptive_icon_foreground: "assets/images/logo.png" # Optional, para sa Android 8+

flutter:
  uses-material-design: true

  assets:
    - assets/images/james_espana.jpeg
    - assets/images/rovannah_delola.jpg
    - assets/images/logo.png
    - assets/models/best_float32.tflite
    - assets/models/labels.txt

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
